### ISSUE TITLE
Update to Godot 3.1

### ISSUE THREAD

**Issue by zcaliptium** [Oen44/Godot-Inventory#2]
This doesn't work on 3.1. Hopefully it require just small fix.

![изображение](https://user-images.githubusercontent.com/8536412/55288933-ff664300-53c7-11e9-9bcf-0b0b0012a959.png)
You should set ``Mouse -> Filter`` to ``Pass``. Othervise GUI event won't get passed into ``_gui_input`` handler.

**Comment by Oen44** [comment]
Thanks, Readme updated.
