### ISSUE TITLE
Missing the project.godot file

### ISSUE THREAD

**Issue by Kemeros** [Oen44/Godot-Inventory#5]
This template is missing the project.godot file, which makes Godot refuse to run the template.

**Comment by allseeingprojectmanager** [comment]
You can import it into an existing project and load the .tcsn file in the main game

**Comment by Kemeros** [comment]
I get that but if someone loads it from the template menu to try it like the other templates, they can't because it gives an error. It's not great for newcomers.

**Comment by Oen44** [comment]
Anyone willing to create PR? I'm not able to take care of that right now.

**Comment by Kemeros** [comment]
Well, i did request it so if it doesn't exist, i'll create it. Imma pop my PR cherry with this hehe. Should have time tonight or tomorrow.

**Comment by Kemeros** [comment]
PR sent.

Please note: The inventory scene file has the correct values in the master branch, but has an incorrect value for the mouse_filter option in the rar files in the two last releases. Please re-export the whole repository for the next release so that the template runs without needing to change options.

**Comment by allseeingprojectmanager** [comment]
> 
> 
> I get that but if someone loads it from the template menu to try it like the other templates, they can't because it gives an error. It's not great for newcomers.

Very true now that you put it that way.
